DROP TABLE IF EXISTS SRV_SD_MAPPING
/
CREATE  TABLE SRV_SD_MAPPING
(
  TYPENAME VARCHAR(64) NOT NULL ,
  REGTYPE VARCHAR(32) NOT NULL ,
  OPERTYPE VARCHAR(64) NOT NULL ,
  VERSION VARCHAR(32) NOT NULL ,
  URIPREFIX VARCHAR(64),
  PRIMARY KEY (TYPENAME,REGTYPE,VERSION)
)
/

DROP TABLE IF EXISTS DECOMPOSER_TASK
/
CREATE TABLE DECOMPOSER_TASK (
  TASKID varchar(64) NOT NULL,
  SERVICEID varchar(64) NOT NULL,
  TENANTID varchar(64) NOT NULL,
  SRVVERSION varchar(16) NOT NULL,
  OPERTYPE varchar(16) NOT NULL,
  SEJOBID varchar(64),
  SERVICECONTENT longtext NOT NULL,
  PROGRESS varchar(16),
  RESULT varchar(64),
  RESULTREASON varchar(255),
  PRIMARY KEY (TASKID)
)
/

DROP TABLE IF EXISTS SRV_RES_MAPPING
/
CREATE TABLE SRV_RES_MAPPING (
  TENANTID varchar(64) NOT NULL,
  SERVICEID varchar(64) NOT NULL,
  RESOURCEID varchar(64) ,
  RESOURCELABEL varchar(32) NOT NULL,
  TYPE varchar(16) ,
  VERSION varchar(8) ,
  RESOURCETYPE varchar(32),
  DEPENDS varchar(128) ,
  ACVTIVEMODE varchar(16),
  RESULT  varchar(64) ,
  RESULTREASON varchar(255)
)
/
CREATE INDEX RES_SVCID_INDEX ON SRV_RES_MAPPING(SERVICEID)
/

DROP TABLE IF EXISTS DECOMPOSER_TASK_LOG
/
CREATE TABLE DECOMPOSER_TASK_LOG (
  TASKID VARCHAR(64)  NOT NULL,
  SEQUENCEID INT NOT NULL,
  TIMESTAP BIGINT NOT NULL,
  DESCRIPTION VARCHAR(255)  NOT NULL,
  RESULT VARCHAR(64)  DEFAULT NULL,
  RESULTREASON VARCHAR(255)  DEFAULT NULL,
  PRIMARY KEY (TASKID,SEQUENCEID)
)
/

