DROP TABLE IF EXISTS SRV_SE_JOB;
/
CREATE TABLE SRV_SE_JOB (
  JOB_ID varchar(64) NOT NULL PRIMARY KEY,
  TENANT_ID varchar(64) NOT NULL,
  SERVICE_ID varchar(64) NOT NULL,
  SRV_VERSION varchar(32) NOT NULL,
  JOB_CONTENT MediumText NOT NULL,
  STATUS varchar(32) NOT NULL,
  RESULT  varchar(64),
  RESULT_REASON varchar(255),
  CREATED_TIME bigint,
  COMPLETED_TIME bigint,
  AUDIT_BASIC_INFO varchar(1024)
)
/

DROP TABLE IF EXISTS SRV_SE_RES_ACTION;
/
CREATE TABLE SRV_SE_RES_ACTION (
  JOB_ID varchar(64) NOT NULL,
  SERVICE_ID varchar(64) NOT NULL,
  RESOURCE_LABEL varchar(64) NOT NULL,
  RES_CONTENT MediumText NOT NULL,
  OPER_TYPE varchar(32) NOT NULL,
  STATUS varchar(32) NOT NULL,
  RESULT  varchar(64),
  RESULT_REASON varchar(255),
  TYPE varchar(64) NOT NULL,
  DEPENDS_ON varchar(512),
  QUERY_URL varchar(255),
  PRIMARY KEY (JOB_ID,RESOURCE_LABEL)
)
/

DROP TABLE IF EXISTS PLUGIN_RULE;
/
CREATE TABLE PLUGIN_RULE (
  TYPENAME VARCHAR(64) NOT NULL ,
  VERSION VARCHAR(64) NOT NULL ,
  OPER_TYPE VARCHAR(64) NOT NULL ,
  URI_PREFIX VARCHAR(255) NOT NULL,
  PRIMARY KEY (TYPENAME,VERSION)
)
/

DROP TABLE IF EXISTS SD_ACTIVE_JOBS
/
create table SD_ACTIVE_JOBS
(
   ID                   VARCHAR(36) NOT NULL,
   VERSION              INT(11) NULL,
   TYPE                 VARCHAR(36) NULL,
   CONTEXT_TAG          BOOLEAN NULL,
   CREATED_AT           BIGINT(20) NULL,
   LAST_SCHEDULED_AT    BIGINT(20) NULL,
   SCHEDULER_ID         VARCHAR(36) NULL,
   ATTRIBUTE            varchar(1024) NULL,
   PRIMARY KEY (ID)
)
/

drop table if exists SD_INSTANCES
/
create table SD_INSTANCES
(
   INSTANCE_ID           VARCHAR(36) NOT NULL,
   REFRESHED_AT          BIGINT(20) NULL,
   PRIMARY KEY (INSTANCE_ID)
)
/
